### ISSUE TITLE
Missing client credentials key [identifier] from options.

### ISSUE THREAD

**Issue by loranger** [SocialiteProviders/Twitter#13]
I've just updated my dependencies and now I have a huge amount of this exception in my log file :

```
InvalidArgumentException was thrown!  Missing client credentials key [identifier] from options.  
#0 /var/web/prod//vendor/league/oauth1-client/src/Client/Server/Server.php(63): League\OAuth1\Client\Server\Server->createClientCredentials(Array) 
#1 /var/web/prod//vendor/socialiteproviders/manager/src/SocialiteWasCalled.php(97): League\OAuth1\Client\Server\Server->__construct(Array) 
#2 /var/web/prod//vendor/socialiteproviders/manager/src/SocialiteWasCalled.php(72): SocialiteProviders\Manager\SocialiteWasCalled->buildOAuth1Provider(Object(Laravel\Socialite\SocialiteManager), 'SocialiteProvid...', 'twitter', 'SocialiteProvid...') 
#3 /var/web/prod//vendor/socialiteproviders/manager/src/SocialiteWasCalled.php(48): SocialiteProviders\Manager\SocialiteWasCalled->buildProvider(Object(Laravel\Socialite\SocialiteManager), 'twitter', 'SocialiteProvid...', 'SocialiteProvid...') 
#4 /var/web/prod//vendor/socialiteproviders/twitter/src/TwitterExtendSocialite.php(15): SocialiteProviders\Manager\SocialiteWasCalled->extendSocialite('twitter', 'SocialiteProvid...', 'SocialiteProvid...') 
#5 [internal function]: SocialiteProviders\Twitter\TwitterExtendSocialite->handle(Object(SocialiteProviders\Manager\SocialiteWasCalled)) 
#6 /var/web/prod//bootstrap/cache/compiled.php(10191): call_user_func_array(Array, Array) 
#7 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(SocialiteProviders\Manager\SocialiteWasCalled)) 
#8 /var/web/prod//bootstrap/cache/compiled.php(10136): call_user_func_array(Object(Closure), Array) 
#9 /var/web/prod//vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(419): Illuminate\Events\Dispatcher->fire('SocialiteProvid...', Array, false) 
#10 /var/web/prod//vendor/socialiteproviders/manager/src/ServiceProvider.php(15): event(Object(SocialiteProviders\Manager\SocialiteWasCalled)) 
#11 [internal function]: SocialiteProviders\Manager\ServiceProvider->boot() 
#12 /var/web/prod//bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array) 
#13 /var/web/prod//bootstrap/cache/compiled.php(1899): Illuminate\Container\Container->call(Array) 
#14 /var/web/prod//bootstrap/cache/compiled.php(1818): Illuminate\Foundation\Application->bootProvider(Object(SocialiteProviders\Manager\ServiceProvider)) 
#15 /var/web/prod//bootstrap/cache/compiled.php(1861): Illuminate\Foundation\Application->register(Object(SocialiteProviders\Manager\ServiceProvider)) 
#16 /var/web/prod//bootstrap/cache/compiled.php(1853): Illuminate\Foundation\Application->registerDeferredProvider('SocialiteProvid...', 'Laravel\\Sociali...') 
#17 /var/web/prod//bootstrap/cache/compiled.php(1842): Illuminate\Foundation\Application->loadDeferredProvider('Laravel\\Sociali...') 
#18 /var/web/prod//vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(225): Illuminate\Foundation\Application->loadDeferredProviders() 
#19 /var/web/prod//vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap() 
#20 /var/web/prod//artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#21 {main} [] []
Level
----------------
CRITICAL
```

I use the following `config/services.php` file :

```php
<?php

return [
...
    'twitter' => [
        'client_id' => env('TWITTER_KEY', 'xxxxxxx'),
        'client_secret' => env('TWITTER_SECRET', 'xyxyxyxyxyxyxyx'),
        'redirect' => env('TWITTER_REDIRECT_URI', 'http://url'),
    ],

];
```

and my `.env` is populated as well :

```
...
TWITTER_KEY=aaaaaaaa
TWITTER_SECRET=abababababab
TWITTER_REDIRECT_URI=http://real_url
```

What am I missing ?

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Manager/commit/7282ff1a137b8b56655cfed3afc87035dd741902
https://github.com/SocialiteProviders/Manager/commit/6c99cb1725ac2b8e5358639bc0f3eb401dc33367

Could you revert these changes in `vendor/socialiteproviders/manager/src/` directory and see if that works? Was a quick fix to make additional config keys optional, might have bricked something.

**Comment by loranger** [comment]
I can confirm : One of those commit breaks (at least) the twitter plugin.

I didn't tried on production so I can't tell what breaks what, but this [specific change](https://github.com/SocialiteProviders/Manager/commit/7282ff1a137b8b56655cfed3afc87035dd741902#diff-208403484e2b1c366933026ee210fc76L131) bricks my artisan if my .env does not contain the environment variables (whereas they are inside `config/services.php`)

**Comment by DraperStudio** [comment]
hmm, this is weird since it just sets the keys that don't exist in the env or services to allow to ignore the additional config keys.

Could you modify the `ConfigRetriever.php` to this:

```
    private function getFromEnv($key)
    {
        $providerKey = "{$this->providerIdentifier}_{$key}";
        $item = env($providerKey);

        if (empty($item)) {
            env($providerKey, null);

            $item = env($providerKey);

            // ignore these for now so additional config keys can be empty
            // throw new MissingConfigException("Configuration for $providerKey is missing.");
        }

        return $item;
    }
```

**Comment by loranger** [comment]
I've replaced the `getFromEnv` method but it doesn't fix the issue.

Here is a way you can reproduce this (I suppose you know those steps by heart but it also makes me sure I didn't miss anything) :

Setup a fresh laravel
```bash
$ laravel new test
$ cd test
$ composer require socialiteproviders/twitter
```

Add the Socialite provider inside `config/app.php`
```php
'providers' => [
    ...
    \SocialiteProviders\Manager\ServiceProvider::class,
```

Add the Socialite provider inside `Providers/EventServiceProvider.php`
```php
    protected $listen = [
        ...
        \SocialiteProviders\Manager\SocialiteWasCalled::class => [
            'SocialiteProviders\Twitter\TwitterExtendSocialite@handle',
        ],
    ];
```

At this step, artisan is not usable anymore :

```bash
$ php artisan

  [InvalidArgumentException]
  Missing client credentials key [identifier] from options.

```

It's a little annoying because I didn't even tried to use twitter, so it should not throw any error, but let say the twitter keys are mandatory and let's add theme to the `config/service.php` :

```php
...
    'twitter' => [
        'client_id' => env('TWITTER_KEY', 'xxxxxxxxx'),
        'client_secret' => env('TWITTER_SECRET', 'xyxyxyxyxyx'),
        'redirect' => env('TWITTER_REDIRECT_URI', 'http://www.twitter.com/callback'),
    ],
```

artisan is still broken :

```bash
$ php artisan

  [InvalidArgumentException]
  Missing client credentials key [identifier] from options.

```

Let's add the key to the `.env` file :

```
TWITTER_KEY=xxxxxxxxx
TWITTER_SECRET=xyxyxyxyxyx
TWITTER_REDIRECT_URI=http://www.twitter.com/callback
```

Then, artisan is back.

I put the default values in my services.php file in order to limit the .env usage in production. Each developer can override the default value with their own .env locally but the deployment ignores this .env file and the app works perfectly (until today :) )

Thanks for your support, by the way.

**Comment by DraperStudio** [comment]
Well that is working as intended as far as I can see.

1. If you have no config in your .env file **(or no .env file at all)** it will throw an MissingConfigException.
2. If you have no config in your services.php it will throw an MissingConfigException.

So if you have no configuration in your services.php and no .env file after deployment it will naturally throw an exception.

**Comment by loranger** [comment]
As you can see in my example (and that's also the case in production), there is a (minimal) .env file, but without any twitter variable. 

They are stored as the second parameter in my services.php file.

**Comment by DraperStudio** [comment]
Yeah I can see that and reproduced it but as I said, you either have to put configuration into the .env file or services.php. Then the setup is complete and the Provider will shut up.

**Comment by DraperStudio** [comment]
We will soon change how the configuration is loaded **(only when the Provider is actually execute)** which should fix the issue with using the .env file and deployment.

**Comment by DraperStudio** [comment]
I have deleted the v2.1.8 release for now so you should be able to use the Provider as usual again.

**Comment by loranger** [comment]
Thank you so much.
You told me to put my configuration in one of the two files, but that's exactly what I thought i did with my services.php : 
```php
'twitter' => [
    'client_id' => env('TWITTER_KEY', 'xxxxxxxxx'),
```
Should do the trick, don't you think ?

I could make the PR if you want, but I'm not really comfortable with the socialite system maybe you could lead me in order to achieve this change ?

**Comment by DraperStudio** [comment]
@loranger Could you replace your `ConfigRetriever.php` with this one? https://github.com/SocialiteProviders/Manager/commit/7c0c77be69e3ac6ce2b9ccb8f04e175322f8a3da

**Comment by loranger** [comment]
This one seems perfect, no more missing credentials error ! 👍

**Comment by DraperStudio** [comment]
Alright, will wait for a reply on https://github.com/SocialiteProviders/Weixin/issues/6 and merge the changes then and tag a new release for the manage.

**Comment by DraperStudio** [comment]
@loranger https://github.com/SocialiteProviders/Manager/releases/tag/v2.1.8
