### ISSUE TITLE
Get user data based on tokens

### ISSUE THREAD

**Issue by ionut-tanasa** [SocialiteProviders/Twitter#7]
Hi.

Quick question. How do I get the user data using directly `oauth_token` and `oauth_secret` ? 

Basically I authenticate using Twitter's SDK for Android. So I already retrieve the tokens inside the app. Then the app calls my API and passes the two tokens for future use because I need to get some extra data with the api.

What I'd want to achieve is something like `Socialite::with('twitter')->userByTokens($token, $secret)`

Is it possible?

**Comment by DraperStudio** [comment]
Nope, Socialite is purely for authentication.
