### ISSUE TITLE
Undefined index: oauth_temp

### ISSUE THREAD

**Issue by olriko** [SocialiteProviders/Twitter#8]
Hello,
I have an error with Socialite Twitter only. When callback's url is call, an error appear : 
`ErrorException in AbstractProvider.php line 94: Undefined index: oauth_temp`

In my controller :
```
    public function uriSocial($social)
    {
        dd(Socialite::with($social)->user());
    }
```
I have the same problem with this guy [https://laracasts.com/discuss/channels/requests/temporary-token-issues-with-socialitetwitter?page=1](url)

If you have a solution, you are welcome :)

Olivier

**Comment by DraperStudio** [comment]
Seems like an issue with sessions on your end because `oauth_temp` could not be stored apparently.

**Comment by DraperStudio** [comment]
@olriko If the issue still exists reopen this issue.
